# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Base box: CentOS 6.5 with LAMP stack installed
  config.vm.box = "smallhadroncollider/centos-6.5-lamp"

  # The box's document root is /var/www/public, so share this dir at that location
  config.vm.share_folder "www", "/var/www", "."

  # Forward port 4567 to the webserver
  config.vm.forward_port 80, 4567

  # Provision script to create database etc.
  config.vm.provision "shell", path: "provision.sh"
end

